Goal: extract variables to be used when modelling
=================================================

```{r setup, echo=FALSE}
opts_chunk$set(cache=FALSE)
```


```{r read data}
## Load data directory information
load("../download/data-info.Rdata")
source("processingFunctions.R")

## Get the file names
files <- list.files(dataDir, pattern="csv", full.names=TRUE)
names(files) <- substr(gsub(".*/", "", files), 1, 4)

## Read data
data <- lapply(files, readPBP)

## Check how big it is in mem
print(object.size(data), units="Mb")

## Save data (12.4 mb)
save(data, file="data.Rdata", compress="gzip")
```


Now that I have finally read in the data, I can now calculate the team stats per year


```{r processByYear}
## List of teams
teams <- sort(unique(data[["2012"]]$off))[-1]

## Get the team stats for all teams in all years, first half only
first <- lapply(data, function(df) {
	res <- lapply(teams, function(team) {
		getTeamStats(team, df, half="first")
	})
	res <- do.call(rbind, res)
})

## Now do the same for the second half only
second <- lapply(data, function(df) {
	res <- lapply(teams, function(team) {
		getTeamStats(team, df, half="second")
	})
	res <- do.call(rbind, res)
})


## Finally, for both halfs
full <- lapply(data, function(df) {
	res <- lapply(teams, function(team) {
		getTeamStats(team, df, half="full")
	})
	res <- do.call(rbind, res)
})

## Save team summaries
save(first, file="first.Rdata")
save(second, file="second.Rdata")
save(full, file="full.Rdata")
```

Next, I have to summarize the data by game

```{r processGames}
## Build data sets that will be used to train the model
gameFirst <- lapply(names(first), function(year) {
	print(paste("Processing year", year))
	gameSummary(first[[year]], data[[year]])
})
print(object.size(gameFirst), units="Mb")

gameFull <- lapply(names(full), function(year) {
	print(paste("Processing year", year))
	gameSummary(full[[year]], data[[year]])
})
print(object.size(gameFull), units="Mb")

## Save information
save(gameFirst, file="gameFirst.Rdata", compress="gzip")
save(gameFull, file="gameFull.Rdata", compress="gzip")

```




