Scrapping Ravens data from ESPN
===============================

Instructions
https://github.com/jtleek/jhsph753/blob/master/assignments/feb5-inclass.md

```{r}
## Load lib and read data
library(XML)
html3 <- htmlTreeParse("http://espn.go.com/nfl/team/_/name/bal/baltimore-ravens", useInternalNodes=TRUE)

```

A bit on xpath syntax
http://www.w3schools.com/xpath/xpath_syntax.asp

```{r}
## Get wins and scores
win <- xpathSApply(html3, "//li[@class='game-status win'] | //li[@class='game-status loss']", xmlValue)
score <- xpathSApply(html3, "//li[@class='score']", xmlValue)
where <- xpathSApply(html3, "//li[@class='game-status']", xmlValue)
team <- xpathSApply(html3, "//li[@class='team-name']", xmlValue)
## From James and Jiawei
dates <- xpathSApply(html3, "//tr[contains(@class,'row team')]/td[2]",xmlValue)


## Get Baltimore and opponent's scores
score.split <- lapply(strsplit(score, "-"), function(x) { gsub(" [0-9]*OT", "", x) })
fooAssign <- function(x, y) { 
	res <- as.numeric(x)
	if(y == "L") {
		res <- rev(res)
	}
	return(res)
}
score.mat <- mapply(fooAssign, score.split, win)

dates <- as.Date(paste(dates, rep(c(2013, 2012), c(4, 16)), sep="-"), format = "%a, %b %d-%Y")

## Group into a data.frame
data <- data.frame(Win = win, Ravens = score.mat[1, ], Opp = score.mat[2, ], Where = where, Team = team, Date = dates)
data
```


```{r}
## Another way of doing it (from Jiawei)
xpathSApply(html3, "//ul[@class='game-schedule']", xmlValue)
```


```{r}
dateDownloaded <- date()
dateDownloaded
save(data, dateDownloaded, file="raw.Rdata")
```


